import { Roboto, Archivo_Black } from "next/font/google";
import "./globals.css";
import BackGound from "./components/Container/Partialjs";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"], // tu peux ajouter d'autres poids si besoin
  variable: "--font-roboto",
});

const archivoBlack = Archivo_Black({
  subsets: ["latin"],
  weight: "400", // obligatoire (Archivo Black n’a qu’un poids)
  variable: "--font-archivo",
  display: "swap",
});
export const metadata = {
  title: "Ngeho Andrianina Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${archivoBlack.variable} antialiased`}
        cz-shortcut-listen="true"
      >
        <BackGound>{children}</BackGound>
      </body>
    </html>
  );
}
